spring:
  profiles:
    active: development
  web:
    resources:
      add-mappings: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/isyeri_egitimi_db
    username: postgres
    password: admin
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  app:
    jwtSecret: mySecretKey123!?$#9123214
    jwtExpirationMs: 1000*3600*24
  security:
    user:
      name: user
      password: 123
security:
  jwt:
    secret: "kadirozerkadirozerkadirozerkadirozerkadirozerkadirozerkadirozerk"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
aws:
  access:
    key: AKIA4MTWNKJ62UQYNG62
  secret:
    key: 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
  s3:
    bucket: isyeri-egitimi
springdoc:
  packages-to-scan: com.isyeriegitimi.backend.controller

